name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.11"

runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v6
      name: Setup uv
      with:
        version: "latest"
        python-version: ${{ inputs.python-version }}
        enable-cache: true

    - run: uv tool install pyproject-parser[cli]>=v0.13.0b1
      shell: bash

    - run: uv sync --all-groups
      shell: bash